name: maid
description: A cross-platform Flutter app for chatting with AI.
publish_to: 'none'

version: 1.3.1+1862

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  image: ^4.1.7
  path_provider: ^2.0.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.0.20
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0
  path: ^1.8.3
  system_info2: ^4.0.0
  http: ^1.1.0
  provider: ^6.1.1
  device_info_plus: ^9.1.1
  langchain: ^0.5.0
  langchain_openai: ^0.5.0
  langchain_ollama: ^0.1.0
  langchain_mistralai: ^0.1.0
  receive_sharing_intent: ^1.6.7
  network_info_plus: ^4.1.0+1
  lan_scanner: ^4.0.0+1
  google_generative_ai: ^0.2.3
  flutter_resizable_container: ^2.0.0
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  maid_llm:
    path: packages/maid_llm
  babylon_tts:
    path: packages/babylon_tts

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/maid.png"
  windows:
    generate: true
    image_path: "assets/maid.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/maid.png"